name: Lint

on: push

jobs:
  check-modules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17.x
      - name: Check module dependencies
        run: |
          go version
          test -z "$(go mod tidy && git status go.* --porcelain)"
          go mod verify

# TODO: Enable linting and address linter errors, https://github.com/grafana/xk6-sql/issues/5
#  run-golangci:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v3
#      - name: Install Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.17.x
#      - name: Retrieve golangci-lint version
#        run: |
#          echo "::set-output name=Version::$(head -n 1 "${GITHUB_WORKSPACE}/.golangci.yml" | tr -d '# ')"
#        id: version
#      - name: golangci-lint
#        uses: golangci/golangci-lint-action@v3
#        with:
#          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
#          version: ${{ steps.version.outputs.Version }}
